
Malicious Devices:  [1]
CR:   0%|                                                                                                         | 0/5 [00:00<?, ?it/s]/home/akshat/.local/lib/python3.9/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(                                                                                                 | 0/10 [00:00<?, ?it/s]
Client Labels:  dict_keys([0, 1, 6, 8, 9, 2, 7, 3, 5, 4])
Client Indexes to use:  [0, 4, 6, 3, 2, 9, 5, 7]
All Labels:  dict_keys([5, 0, 4, 1, 9, 2, 3, 6, 7, 8])








CR:   0%|                                                                                                         | 0/5 [01:34<?, ?it/s]
Traceback (most recent call last):
  File "/home/akshat/project/train_loop.py", line 196, in <module>
    train_object.train()
  File "/home/akshat/project/train_loop.py", line 152, in train
    to_df.append(phases.phase3(self.global_network, local_weights, dynamic_datasets, args=self.args, device=self.device))
  File "/home/akshat/project/phases.py", line 77, in phase3
    for i in tqdm(range(len(dynamic_datasets)), desc= "Global Model Training: "):
TypeError: 'module' object is not callable